name: Systemli - Your friendly tech collective
highlighter: pygments
source: ./src
include: [.well-known,.htaccess]

gems:
  - octopress-paginate

pagination:
  limit: 5

#### certs ####
fp_www_systemli: "02:0E:89:B1:BC:46:01:44:B4:E8:9B:28:5E:23:93:71:FD:2B:49:8D"
fp_tem_li: "3A:F5:FE:76:C4:78:DE:48:00:5F:C9:ED:D7:66:CD:2D:79:C1:FF:36"
fp_jabber_systemli: "25:6B:2F:16:A5:22:9A:DE:88:11:A3:7C:C5:68:BE:04:75:8E:10:5D"
fp_mail_systemli: "02:7E:86:57:5E:97:89:4D:7C:69:18:96:29:ED:94:23:BF:11:8C:14"
fp_wiki_systemli: "A9:43:E3:99:0F:CF:9F:84:2A:A2:0B:DB:33:BC:00:41:78:BC:04:6F"
fp_demoticker: "1D:3A:7A:12:A3:E7:AF:84:1D:F2:25:8A:56:23:F8:AE:29:00:D7:91"

#### tor hidden services ####
onion_jabber_systemli: x5tno6mwkncu5m3h.onion
onion_mail_systemli: h2qkxasmmqdmyiov.onion
